### ISSUE TITLE
#2021Tencent Rhino-bird Open-source Training Program—TencentOS Tiny#

### ISSUE THREAD

**Issue by tencent-adm** [Tencent/OpenSourceTalent#11]
**腾讯犀牛鸟开源人才培养计划
Tencent Rhino-bird Open-source Training Program**
为响应国家十四五规划的开源战略，腾讯于2021年5月发布“首届腾讯犀牛鸟开源人才培养计划”，希望企业界和教育界形成合力，打造面向高校学生的开源课程和开源实践培养方案，培育开源人才，普及开源文化，助力开源人才生态的发展。

首届项目由教育部计算机教学指导委员会、教育部软件工程教学指导委员会、中国信息通信研究院作为联合指导单位，包括开源基础培训、开源进阶研学、开源项目实战三个环节，项目涉及云原生、微服务、容器、AI、大数据、前端、物联网/边缘计算等多项技术热点。

各位同学报名即可参加线上开源系列课程，学习开源知识，对话学界及产业界大咖。其中入选开源项目实战的学生将在导师的一对一指导下，利用暑假开展编程实战，并有机会获得腾讯开源贡献者证书（目前全球只发出了10+张）。

更多项目信息请看：https://opensource.tencent.com/summer-of-code
 
### 项目简介
腾讯面向物联网领域开发的实时操作系统，具有低功耗，低资源占用，模块化，安全可靠等特点，可有效提升物联网终端产品开发效率； 提供精简的 RTOS 内核，内核组件可裁剪可配置，可快速移植到多种主流 MCU (如 STM32 全系列)及模组芯片上。覆盖IoT主流应用场景，支持硬件平台数量超60+，包括STM32、NXP、华大半导体等多家MCU和模组厂家。

TencentOS Tiny中文官网：https://cloud.tencent.com/product/tos-tiny
TencentOS Tiny项目主页：https://github.com/Tencent/TencentOS-tiny

### 项目导师
汪礼超，TencentOS tiny核心架构师, 联系方式微信supowang
赵健，TencentOS tiny架构师
王世伟，TencentOS tiny布道师

### 导师寄语
近年来，随着5G、NB-IoT、4G cat1等广域物联网技术的日渐成熟，物联网市场呈井喷式发展。目前TencentOS Tiny项目已经捐赠给中国开放原子开源基金会，将持续配合广大开发者、合作伙伴，进一步扩展开发者和应用生态。欢迎同学们积极参与！

### 编程任务
**项目1：TencentOS Tiny 物联网操作系统上支持js框架**
任务：
    

- [ ] 开发完成 JS framework、js runtime 等js基础运行环境；
- [ ]     基于JS应用框架提供相应的js编译工具或者操作脚本；
- [ ]     完成类似小程序的js app demo演示
- [ ]     完成基础测试和技术指导文档编写

需要的基础：C语言、JS、RTOS、TencentOS Tiny物联网操作系统

<br>

**项目2. TencentOS Tiny 物联网操作系统上支持Rust语言框架**

任务：
    

- [ ] 开发完成Rust基础运行环境；
- [ ]     基于Rust应用框架提供相应的编译工具或者操作脚本；
- [ ]     完成rust app demo演示
- [ ]     完成基础测试和技术指导文档编写

需要的基础：C语言、rust、RTOS、TencentOS Tiny物联网操作系统
参考例子：https://github.com/Tencent/TencentOS-tiny/tree/master/examples/tos_meets_rust
请基于该案例进行优化，要求rust运行框架解耦，rust app能灵活快速编译部署

<br>

**项目3. TencentOS Tiny 物联网操作系统 AI组件开发**

任务
    

- [ ] 开发AI 推理框架，可选TensorFlow Lite Micro或者其他推理引擎；
- [ ]     要求AI框架可以运行在低资源的MCU上，比如STM32 、NXP等MCU；
- [ ]     AI框架组件化，可以裁剪可移植；
- [ ]    AI框架可完成基础的人脸识别、物体识别、语言识别等能力，并提供相应demo；
- [ ]     完成基础测试和技术指导文档编写

需要的基础：  C语言、AI、TensorFlow 、RTOS、TencentOS Tiny物联网操作系统
参考例子：https://github.com/Tencent/TencentOS-tiny/tree/master/components/ai/tflite_micro
<br>
**项目4：基于STM32CubeMX 或者MDK完成第三方TencentOS Tiny pack和软件包封装，可以使用STM32CubeMX或者MDK pack直接生成适合不同MCU的TencentOS Tiny工程**

参考文档 ARM MDK PACK制作：https://arm-software.github.io/CMSIS_5/Pack/html/cp_Packs.html
STM32CubeMX 第三方软件包制作：https://www.stmicroelectronics.com.cn/resource/en/user_manual/dm00432311-development-guidelines-for-stm32cube-expansion-packages-stmicroelectronics.pdf
<br>

### 联系导师
汪礼超，TencentOS tiny核心架构师 ，Email：supowang@tencent.com  微信：supowang 
赵健，TencentOS tiny架构师，jackjzhao@tencent.com

**Comment by Derekduke** [comment]
请问关于项目任务细节的疑惑，是这个issue里提出吗？
