### ISSUE TITLE
#2021Tencent Rhino-bird Open-source Training Program—TKEStack#

### ISSUE THREAD

**Issue by tencent-adm** [Tencent/OpenSourceTalent#12]
**腾讯犀牛鸟开源人才培养计划
Tencent Rhino-bird Open-source Training Program**
为响应国家十四五规划的开源战略，腾讯于2021年5月发布“首届腾讯犀牛鸟开源人才培养计划”，希望企业界和教育界形成合力，打造面向高校学生的开源课程和开源实践培养方案，培育开源人才，普及开源文化，助力开源人才生态的发展。

首届项目由教育部计算机教学指导委员会、教育部软件工程教学指导委员会、中国信息通信研究院作为联合指导单位，包括开源基础培训、开源进阶研学、开源项目实战三个环节，项目涉及云原生、微服务、容器、AI、大数据、前端、物联网/边缘计算等多项技术热点。

各位同学报名即可参加线上开源系列课程，学习开源知识，对话学界及产业界大咖。其中入选开源项目实战的学生将在导师的一对一指导下，利用暑假开展编程实战，并有机会获得腾讯开源贡献者证书（目前全球只发出了10+张）。

更多项目信息请看：https://opensource.tencent.com/summer-of-code

### 项目简介
TKEStack是一个开源的，集健壮性和易用性于一身的企业级容器编排引擎，为在生产环境中部署容器的组织提供一个统一的容器管理平台，以极简的向导式界面提供了容器应用的全生命周期管理能力，帮助用户在私有云，混合云环境中敏捷、高效地构建和发布应用程序，满足 IT 运维要求，并增强 DevOps 团队的能力。

TKEStack在线手册：https://tkestack.github.io/docs/

### 项目导师
汝英哲，TKEStack开源项目负责人

### 导师寄语
随着容器以及K8S的快速发展和广泛应用，云计算领域正在迎来云原生时代，TKEStack是腾讯开源的优秀云原生容器平台，希望同学们通过对TKEStack的学习和实践，能够了解云原生领域最新的技术，融入开源生态，磨炼技术，成长为独当一面的人才。

### 编程任务
● TKEStack 集群CIS安全基线扫描分析

*任务描述*：
为了提供更安全的K8s集群，有必要使集群遵循安全的配置基线。

*建议方案*：
建议使用Center for Internet Security(CIS) benchmarks 来评估和分析集群的安全性。

*具体工作*：
1. 阅读和理解kubernetes的CIS基准
2. 使用kube-benchtools检查由tkestack创建的集群
3.根据分析结果，提出相应的安全建议
4. 向tkestack提交PR以增强集群的安全性

*参考*：
1. https://www.cisecurity.org/benchmark/kubernetes/
2. https://wiki.aquasec.com/display/containers/CIS+Kubernetes+Benchmark

● 支持 built-in 安装 storage 存储

*任务描述*：
目前，TKEStack不提供存储解决方案作为开箱即用的特性，导致终端用户很难使用有状态应用程序，此外，内部组件(如镜像仓库和InfluxDB等)依赖master[0]上的本地存储,这意味着如果master[0]异常，TKEStack HA将受影响。

*建议方案*：
在TKEStack global集群上启用minio作为存储解决方案，为全局集群和业务集群创建一个默认存储类

*具体工作*：
1. 安装minio到全局集群的helm chart:  https://github.com/minio/operator/tree/master/helm
2. 动态PV使用csi机制: https://github.com/minio/direct-csi
3. 将默认 storage class导出到最终用户

*参考*：
1. https://www.cnblogs.com/panwenbin-logs/p/12196286.html
2. https://blog.csdn.net/weixin_42914965/article/details/106035429
3. https://juejin.cn/post/6844904152284266503

● 支持创建边缘独立集群

*任务描述*：
SuperEdge是面向边缘计算的开源容器管理系统，它将Kubernetes强大的容器编排和调度能力扩展到了边缘。SuperEdge提供了工具用于创建边缘集群，希望也能通过tkestack来创建和管理边缘集群。

*建议方案*：
SuperEdge提供了edgeadm工具来创建边缘集群，在tkestack中利用该工具来创建边缘集群。

*具体工作*：
1. 学习SuperEdge项目并使用edgeadm工具创建边缘集群
2. 扩展tkestack，以支持创建边缘集群形式的tkestack
3.支持在tkestack中管理边缘集群

*参考*：
1. https://github.com/superedge/superedge
2. https://github.com/superedge/superedge/blob/main/docs/installation/install_edge_kubernetes.md

###  联系导师
汝英哲，TKEStack开源项目负责人：yingzheru@tencent.com

**Comment by huxiaoliang** [comment]
The details of task #2: https://github.com/tkestack/tke/issues/899

**Comment by ruyingzhe** [comment]
detail for 1:  tkestack/tke#1367

**Comment by ruyingzhe** [comment]
detail for 3: tkestack/tke#1368
