### ISSUE TITLE
腾讯犀牛鸟开源人才培养计划 2024年是否继续开展？

### ISSUE THREAD

**Issue by heliang666s** [Tencent/OpenSourceTalent#49]
如题，如果开展的话，在校生需要做什么准备呢？

**Comment by Vitalis001** [comment]
如题，不知2024年是否继续开展？？？

**Comment by SingaCycle** [comment]
同问

**Comment by tencent-adm** [comment]
> 如题，如果开展的话，在校生需要做什么准备呢？

2024腾讯犀牛鸟开源人才培养将于6月28日正式推出，欢迎加入官方活动QQ大群859260607关注最新进度，[活动官网](https://opensource.tencent.com/summer-of-code)将于7月28日刷新开启！敬请期待 ：）

**Comment by tencent-adm** [comment]
> 如题，不知2024年是否继续开展？？？


继续开展哈，感谢同学关注！2024腾讯犀牛鸟开源人才培养将于6月28日正式推出，欢迎加入官方活动QQ大群859260607关注最新进度，[活动官网](https://opensource.tencent.com/summer-of-code)将于7月28日刷新开启！敬请期待 ：）

**Comment by tencent-adm** [comment]
> 同问


感谢同学关注！2024腾讯犀牛鸟开源人才培养将于6月28日正式推出，欢迎加入官方活动QQ大群859260607关注最新进度，[活动官网](https://opensource.tencent.com/summer-of-code)将于7月28日刷新开启！敬请期待 ：）
