### ISSUE TITLE
#2021Tencent Rhino-bird Open-source Training Program—Apache InLong（原Apache TubeMQ）#

### ISSUE THREAD

**Issue by tencent-adm** [Tencent/OpenSourceTalent#5]
**腾讯犀牛鸟开源人才培养计划
Tencent Rhino-bird Open-source Training Program**
为响应国家十四五规划的开源战略，腾讯于2021年5月发布“首届腾讯犀牛鸟开源人才培养计划”，希望企业界和教育界形成合力，打造面向高校学生的开源课程和开源实践培养方案，培育开源人才，普及开源文化，助力开源人才生态的发展。

首届项目由教育部计算机教学指导委员会、教育部软件工程教学指导委员会、中国信息通信研究院作为联合指导单位，包括开源基础培训、开源进阶研学、开源项目实战三个环节，项目涉及云原生、微服务、容器、AI、大数据、前端、物联网/边缘计算等多项技术热点。

各位同学报名即可参加线上开源系列课程，学习开源知识，对话学界及产业界大咖。其中入选开源项目实战的学生将在导师的一对一指导下，利用暑假开展编程实战，并有机会获得腾讯开源贡献者证书（目前全球只发出了10+张）。

更多项目信息请看：https://opensource.tencent.com/summer-of-code
 
### 项目简介
Apache InLong（原Apache TubeMQ）：是腾讯自研分布式消息中间件系统（MQ），专注服务大数据场景下海量数据的高性能存储和传输，在稳定性、性能以及成本方面有独特的优势。不仅在腾讯内部多个重要业务部门落地多年，同时通过在Apache社区的开源，已在多个外部公司内进行了线上业务应用，目前TubeMQ正依托社区进行项目孵化和改进，走上了社区开放治理之路。

Apache InLong（原Apache TubeMQ）项目主页：http://inlong.apache.org/en-us/

### 项目导师
张国成，Apache TubeMQ社区PPMC

### 导师寄语
Apache TubeMQ是专注服务大数据场景的分布式万亿级的消息中间件，并且同一套版本在腾讯内部环境上使用。通过这个项目你既可以了解开源社区的玩法，同时还可以了解到真实的线上项目该如何开发和改进。
 
### 编程任务
1. 完善特性：包括新特性开发，单元测试，文档撰写；
2. 代码优化：对已有代码进行代码检视，以模块化方式优化已有的代码实现
3. 认领项目issue，进行代码优化及改进。

联系导师
张国成，Apache TubeMQ社区PPMC：gosonzhang@tencent.com

**Comment by LeBW** [comment]
您好，我对这个项目非常感兴趣，不知道有没有机会进一步沟通，了解详细信息呢？
